### ISSUE TITLE
<br> tag doesn't recognized as a line break/new line (nor does double spaces and back slashes)

### ISSUE THREAD

**Issue by Antiz96** [charmbracelet/glamour#152] opened 2022-05-23 17:13 UTC
Hi,

It looks like the various markdown's possibilities to add a line break/new line are not recognized (I'm using glow v1.4.1).
Indeed, the double spaces issue has already been raised in #84 and the back slashes issue has been raised in #90, but it seems like the `<br>` tags doesn't work as well (it actually just does an extra space):
```
$ cat test.md
Hello
<br>
World
```
**Expectation:**
```
$ glow test.md

  Hello
  World

```
**Reality:**
```
$ glow test.md

  Hello  World

```
That would be awesome if those markdown standards could be implement ! :)

By the way, someone in [charmbracelet/glow/#212](https://github.com/charmbracelet/glow/issues/212) mentioned that those issues were already technically fixed in **glamour** and that it was now more a **glow** setting issue.

If I posted that issue in the wrong repo, I do apologize.

Anyway, thanks for your awesome work !

**Comment by muesli** [comment] 2022-10-12 02:33
Closing as dupe of #83 and #84.

**Closed by muesli** 2022-10-12 02:33 UTC
Labels: duplicate
