### ISSUE TITLE
Quotes don't render correctly when using --width

### ISSUE THREAD

**Issue by ceuk** [charmbracelet/glamour#93] opened 2020-12-10 14:31 UTC
To recreate: 

`echo "> this is a long quote that will be wrapped when I set the width to 20 causing it to break to a new line without prepending the quote indicator" > /tmp/glow-test && glow /tmp/glow-test --width=20`

Output:

```
  │ this is a long 
  │ quote that    
  will            
  │ be wrapped    
  when            
  │ I set the     
  width           
  │ to 20 causing  
  │ it to break to 
  │ a new line     
  │ without        
  │ prepending the 
  │ quote         
  indicator  
```

Expected:

```
  │ this is a long
  │ quote that will
  │ be wrapped when I
  │ set the width to
  │ 20 causing it to
  │ break to a new
  │ line without
  │ prepending the
  │ quote indicator

```

**Comment by noerw** [comment] 2020-12-16 00:30
Internally probaby the same issue as #56

**Comment by muesli** [comment] 2022-10-12 02:04
Closing as dupe of #172 (even though yours came first). Thanks for reporting the issue!

**Closed by muesli** 2022-10-12 02:04 UTC
Labels: duplicate
